---
# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2024 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Install nano editor if not present
# Change the /etc/nanorc tabsize from default 8 to 4.
# on RHEL/CENTOS/Debian hosts
- hosts: "{{ hosts | default('localhost') }}"
  name: "Install nano rpm on RHEL / CENTOS / Debian hosts"
  become: true

# vars:
#   print_information: true

  tasks:
    - import_tasks: ../common/common_information.yml

    - name: "Include Yum installer"
      import_tasks: ../rhel/editors/yum-setup-nano.yml
      when: (ansible_os_family == 'RedHat')
            and
            (ansible_lsb.major_release|int >= 5 and
             ansible_lsb.major_release|int <= 7)
      changed_when: false

    - name: "Include DNF installer"
      import_tasks: ../rhel/editors/dnf-setup-nano.yml
      when: ((ansible_os_family == 'RedHat')
            and
            (ansible_lsb.major_release|int >= 8))
      changed_when: false

    - name: "Include APT installer"
      import_tasks: ../debian/editors/apt-setup-nano.yml
      when: ansible_os_family == 'Debian'
      changed_when: false

    # Does /etc/nanorc exist?
    - name: "Check for /etc/nanorc"
      stat:
        path: /etc/nanorc
      register: nanorc_present
      changed_when: false

    # Set out tabsize to 4.
    - name: "Set nano tabsize to 4"
      lineinfile:
        dest: /etc/nanorc
        backup: true
        backrefs: true
        regexp: "^# set tabsize 8"
        line: "set tabsize 4"
      when: nanorc_present.stat.exists == true
