
---
# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2023 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# RHSB-2022-004 X.509 Email Address Buffer Overflow - OpenSSL
# cve-2022-3602 and cve-2022-3786
# on RHEL/CENTOS hosts
- hosts: "{{ hosts | default('localhost') }}"
  name: "Are we vulnerable to cve-2022-3602 & cve-2022-3786 on RHEL/CENTOS hosts"
  become: yes

#  vars:
#       print_information: true

  tasks:
    - import_tasks: ../../common/common_information.yml

    - name: "RHSB-2022-004 X.509 Email Address Buffer Overflow - OpenSSL - (CVE-2022-3602 / cve-2022-3786)"
      script: scripts/cve-2022-3602--2022-11-02-1357.sh -n
      when: (ansible_os_family == 'RedHat')
            and
            (ansible_lsb.major_release|int >= 9)
      register: vulnerable_info
      changed_when: false
      failed_when: vulnerable_info.rc > 0
