#!/bin/sh

# %BEGIN_COPYRIGHT%
# 
# Copyright 2015-2021 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Ansible script to query the existance of a RPM package.
#
# Returns: JSON string:
# { 
#	"found": true/false ,
#	"rpm_count": "Count of number of RPM packages" ,
#	"rpm_names": "String of RPM package names"
# }

RPM_PACKAGE=${1}
RPM_COUNT=0

if [ ! -z ${RPM_PACKAGE} ]; then

	RPM_COUNT=$(rpm -qa | grep -i ${RPM_PACKAGE} | wc -l)

	RPM_NAMES=$(rpm -qa | grep -i ${RPM_PACKAGE} | sort)
fi

if [[ ${RPM_COUNT} =~ 0 ]]; then

	printf '{ "found": false , "rpm_count": "0" , "rpm_names": "" }'

else

	# Remove any newline chars from the name and replace with %%.
	# %% will be later substituded in the output display.
	RPM_NAMES=${RPM_NAMES//$'\n'/%%}

	# Cut the last char off the end of the string.
	#RPM_NAMES=${RPM_NAMES%?}

	# Debug
	#printf "${RPM_NAMES}\n"

	printf '{ "found": true  , "rpm_count": "%s" , "rpm_names": "%s" }' \
			 "${RPM_COUNT}" \
			 "${RPM_NAMES}"

fi
