#!/bin/sh

# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2025 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Ansible script to yum/dnf repolist all.

PACKAGE_MANAGER=yum

if [ ! -z ${1} ]; then
	if [ X"${1}" = X"dnf" ]; then
		PACKAGE_MANAGER=dnf
	fi

	shift
fi

REPO_TYPE="all"

if [ ! -z ${1} ]; then
	REPO_TYPE="${1}"
fi

TEMP_FILE=$(mktemp --tmpdir ansible_yum_dnf_repo_tmp.XXXXXXXXX)

# Debug
#printf "Temp Filename = ${TEMP_FILE}\n\n"

# Grab the Repo list.
${PACKAGE_MANAGER} repolist ${REPO_TYPE} >& ${TEMP_FILE}

REPO_LIST=$(cat ${TEMP_FILE})

printf "${REPO_LIST}\n"

# Remove temp file
unlink ${TEMP_FILE}
