---
# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2024 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Execute pkg_info on OpenBSD hosts to list installed packages.
- hosts: "{{ hosts | default('localhost') }}"
  name: "Execute pkg_info on OpenBSD hosts to list installed packages"
  become: true

  tasks:
    - import_tasks: ../../common/common_information.yml

    - name: "pkg_info fetch installed packages"
      script: scripts/pkg_info_list_installed
      when: ansible_os_family == 'OpenBSD'
      register: pkg_info
      changed_when: false
      failed_when: pkg_info.rc > 0

    # Pkg reporting
    - name: "Print packages found"
      local_action:
        command printf "%s%s\n\n{{ (pkg_info.stdout|from_json).pkg_list.replace('%%', '\n') }}\n\n" \
        "Approximately {{ (pkg_info.stdout|from_json).pkg_count }} " \
        "packages found - \n\n"
      when:
        pkg_info is defined
        and (pkg_info.stdout|from_json).found
      changed_when: false

    - name: "Print no packages found"
      local_action:
        command printf "%s" \
        "No Packages found."
      when:
        pkg_info is defined
        and not (pkg_info.stdout|from_json).found
      changed_when: false

    - name: "Print pkg_info error"
      local_action:
        command printf "%s\n{{ (pkg_info.stdout|from_json).error_msg.replace('%%', '\n') }}\n" \
        "An error occurred"
      when:
        pkg_info is defined
        and (pkg_info.stdout|from_json).error_msg | length > 0
      changed_when: false
      failed_when: true

#    - name: "debug"
#      debug:
#        var: pkg_info
