---
# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2024 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Enable / Disable services at boot time on RHEL/CENTOS hosts
- hosts: "{{ hosts | default('localhost') }}"
  name: "Enable / Disable services at boot time"
  become: true

  vars_prompt:
    - name: "service_name"
      prompt: 'Enter the name of the service (multiple seperated by a comma)'
      private: false

    - name: "service_enable"
      prompt: "(E)nable or (D)isable the service (e / d)\nNOTE: this will appy to all services listed above"
      private: false

#  vars:
#    print_information: true

  tasks:
    - import_tasks: ../common/common_information.yml

    - name: "Invalid service name"
      local_action:
        command printf "%s" \
        "Invalid service name."
      when: service_name | length == 0
      failed_when: true

    - name: "Invalid service enable / disable"
      local_action:
        command printf "%s" \
        "Invalid service enable / disable selection."
      when: service_enable not in ['e', 'd']
      failed_when: true

    - name: "Set Service enabled"
      set_fact:
        service_enabled: "{{ (service_enable == 'e') | ternary('yes','no') }}"
      changed_when: false

    - name: "Service enable / disable at boot"
      service:
        name: "{{ item }}"
        enabled: "{{ service_enabled }}"
      with_items:
        - "{{ service_name.split(',') }}"
