---
# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2025 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# List the files of an installed RPM.
- hosts: "{{ hosts | default('localhost') }}"
  name: "List the files of an RPM installed on RHEL/CENTOS hosts"

  vars_prompt:
    - name: "rpm_package"
      prompt: "\nEnter the RPM package name(s)\n(seperated by a comma for mutiple)"
      private: false

  vars:
    print_rpm_info: ""
#    print_information: true

  tasks:
    - import_tasks: ../../common/common_information.yml

    - name: "Redhat OS Family?"
      local_action:
        command printf "%s" \
        "Not a RedHat OS Family"
      failed_when: ansible_os_family != 'RedHat'

    - name: "Invalid RPM package name"
      local_action:
        command printf "%s" \
        "Invalid RPM package name."
      when: rpm_package | length == 0
      failed_when: true

    - name: "List files of installed RPMs"
      script: scripts/rpm_list_files  "{{ item }}"
      register: rpm_info
      when: ansible_os_family == 'RedHat'
      changed_when: false
      with_items:
        - "{{ rpm_package.split(',') }}"

    - name: "Print RPM files v2"
      local_action:
        command printf "\n\n%s\n\n{{ (item.stdout|from_json).found_list.replace('%%', '\n') }}\n\n" \
        "{{ item.item }}"
      changed_when: false
      when:
        ansible_version.major|int == 2
        && ansible_os_family == 'RedHat'
      with_items:
        - "{{ rpm_info.results }}"
      loop_control:
        label: "\n\n{{ item.item }}\n\n{{ (item.stdout|from_json).found_list.replace('%%', '\n') }}\n\n"
