---
# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2023 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

#  Define Repository URLs on RHEL/CENTOS hosts

- name: "Set distribution facts"
  set_fact:
    ius_distribution_abbrev: "{{ (ansible_distribution == 'CentOS') | ternary('centos', 'rhel') }}"

- name: "Repo not Defined?"
  local_action: command printf "Unknown Repository selected.\n\n"
  when:
    repo_name not in ['cert', 'epel', 'ius', 'remi', 'repoforge', 'percona']
  failed_when: true
  changed_when: false

- name: "Are we EPEL?"
  set_fact:
    repo_url:
      "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: repo_name == 'epel'
  changed_when: false

- name: "Are we IUS?"
  set_fact:
    repo_url:
      "https://{{ ius_distribution_abbrev }}{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm"
  when: repo_name == 'ius'
  changed_when: false

- name: "Are we REMI?"
  set_fact:
    repo_url:
      "http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
  when: repo_name == 'remi'
  changed_when: false

- name: "Are we Repoforge?"
  set_fact:
    repo_url:
      "http://repository.it4i.cz/mirrors/repoforge/redhat/el\
           {{ ansible_distribution_major_version }}/en/\
           {{ ansible_architecture }}/rpmforge/RPMS/\
           rpmforge-release-0.5.3-1.el{{ ansible_distribution_major_version }}.rf.{{ ansible_architecture }}.rpm"
  when: repo_name == 'repoforge'
  changed_when: false

- name: "Are we Percona release?"
  set_fact:
    repo_url:
      "https://www.percona.com/redir/downloads/percona-release/redhat/percona-release-0.1-3.noarch.rpm"
  when: repo_name == 'percona'
  changed_when: false

- name: "Are we Cert Forensics EL release?"
  set_fact:
    repo_url:
      "https://forensics.cert.org/cert-forensics-tools-release-el{{ ansible_distribution_major_version }}.rpm"
  when: repo_name == 'cert' and ansible_distribution != 'Fedora'
  changed_when: false

- name: "Are we Cert Forensics Fedora release?"
  set_fact:
    repo_url: "https://forensics.cert.org/cert-forensics-tools-release-{{ ansible_distribution_major_version }}.rpm"
  when: repo_name == 'cert' and ansible_distribution == 'Fedora'
  changed_when: false

- name: "Print repository URL we are installing"
  local_action:
    command printf "%s\n\n" \
    "repo_url  {{ repo_url }}"
  failed_when: false
  changed_when: false
