---
# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2025 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Update Deb package to the latest release.
# on Debian/Ubuntu hosts
- name: "Enable / Disable APT sources"
  script: scripts/enable_disable_apt_sources -d="{{ disable_source }}" -e="{{ enable_source }}"
  when: ansible_os_family == 'Debian'
  register: apt_info
  changed_when: false
  failed_when: apt_info.rc > 0

- name: "APT upgrade Deb package"
  apt:
    name: "{{ deb_package.split(',') }}"
    state: latest
  when: ansible_os_family == 'Debian'
  # register: apt_deb_update

# - name: "debug"
#   local_action: command printf "\n\n{{ apt_deb_update }}\n\n"
#   changed_when: false
