---
# %BEGIN_COPYRIGHT%
#
# Copyright 2015-2023 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Upgrade DEB package to the latest release on Debian/ubuntu hosts
- hosts: "{{ hosts | default('localhost') }}"
  name: "Upgrade Deb package(s) to the latest release on Debian/Ubuntu hosts"
  become: true

  vars_prompt:
    - name: "deb_package"
      prompt: "\nEnter the Deb package name(s) \n(seperated by a comma for multiple or '*' to install all deb upgrades)"
      private: false

    - name: "disable_source"
      prompt: "\nEnter the list of Source filename(s) to disable\n(seperated by a comma for multiple, leave blank for none)"
      private: false

    - name: "enable_source"
      prompt: "\nEnter the list of Source filename(s) to enable\n(seperated by a comma for multiple, leave blank for none)"
      private: false

  vars:
    print_apt_update: ""
#    print_information: true

  tasks:
    - import_tasks: ../../common/common_information.yml

    - name: "Invalid Deb package name"
      local_action: command printf "Invalid Deb package name."
      when: deb_package | length == 0
      failed_when: true

    - import_tasks: ../common/common_apt_fix_vars.yml

    - name: "Include APT upgrade Deb"
      import_tasks: apt-upgrade-deb.yml
      when: ansible_os_family == 'Debian'
      changed_when: false
